GasthausWebApp3Bhwii/Models/BestellPosition.cs
namespace GasthausWebApp3Bhwii.Models;

public class BestellPosition
{
    public int bestellpositionid { get; set; }
    public int produktid { get; set; }
    public int bestellid { get; set; }
    
}

GasthausWebApp3Bhwii/Models/Bestellung.cs
namespace GasthausWebApp3Bhwii.Models;

public class Bestellung
{
    public int bestellid { get; set; }
    public string preis { get; set; }
    public string menge { get; set; }
    public int mitarbeiterid { get; set; }
    public int tischid { get; set; }
    public int gastid { get; set; }
}

GasthausWebApp3Bhwii/Models/ErrorViewModel.cs
namespace GasthausWebApp3Bhwii.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

GasthausWebApp3Bhwii/Models/Gast.cs
namespace GasthausWebApp3Bhwii.Models;

public class Gast
{
    public int Gastid { get; set; }
    public string vorname { get; set; }
    public string nachname { get; set; }
    public TimeSpan aufenthaltdauer { get; set; }
}

GasthausWebApp3Bhwii/Models/Mitarbeiter.cs
using System.Runtime.InteropServices.JavaScript;

namespace GasthausWebApp3Bhwii.Models;

public class Mitarbeiter
{
    public int mitarbeiterid { get; set; }
    public string vorname { get; set; }
    public string nachname { get; set; }
    public DateTime geburtsdatum { get; set; }
}

GasthausWebApp3Bhwii/Models/Produkt.cs
namespace GasthausWebApp3Bhwii.Models;

public class Produkt
{
    public int produktid { get; set; }
    public string bezeichnung { get; set; }
    public double preis { get; set; }
    public string typ { get; set; }
}

GasthausWebApp3Bhwii/Models/Tisch.cs
namespace GasthausWebApp3Bhwii.Models;

public class Tisch
{
    public int Tischid { get; set; }
    public double laenge { get; set; }
    public double breite { get; set; }
    public double hoehe { get; set; }
}

GasthausWebApp3Bhwii/Controllers/BestellPositionController.cs
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GasthausWebApp3Bhwii.Controllers;

public class BestellPositionController : Controller
{
    // GET
    public IActionResult Index()
    {
        BestellungPositionRepository repo_bestellposition = new BestellungPositionRepository();
        List<BestellPosition> mybestellposition = repo_bestellposition.GetAllBestellPositionen();
        
        
        return View(mybestellposition);
    }
}

GasthausWebApp3Bhwii/Controllers/BestellungController.cs
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GasthausWebApp3Bhwii.Controllers;

public class BestellungController : Controller
{
    // GET
    public IActionResult Index()
    {
        BestellungRepository repo_bestellung = new BestellungRepository();
        List<Bestellung> mybestellung = repo_bestellung.GetAllBestellungen();
        
        
        return View(mybestellung);
    }
}

GasthausWebApp3Bhwii/Controllers/GastController.cs
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GasthausWebApp3Bhwii.Controllers;

public class GastController : Controller
{
    // GET
    public IActionResult Index()
    {
        GastRepository repo_gast = new GastRepository();
        List<Gast> myGast = repo_gast.GetAllGaeste();
        
        
        return View(myGast);
    }
}

GasthausWebApp3Bhwii/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;

namespace GasthausWebApp3Bhwii.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {

        TischRepository repo_tisch = new TischRepository();
        List<Tisch> mytische = repo_tisch.GetAllTisches();

        // GastRepository repo_gast = new GastRepository();
        // List<Gast> mygasts = repo_gast.GetAllGaeste();
        
        
        return View(mytische);
        // return View();
        
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

GasthausWebApp3Bhwii/Controllers/MitarbeiterController.cs
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GasthausWebApp3Bhwii.Controllers;

public class MitarbeiterController : Controller
{
    // GET
    public IActionResult Index()
    {
        MitarbeiterRepository repo_mitarbeiter = new MitarbeiterRepository();
        List<Mitarbeiter> myMitarbeiter = repo_mitarbeiter.GetAllMitarbeiter();
        
        
        return View(myMitarbeiter);
    }
}

GasthausWebApp3Bhwii/Controllers/ProduktController.cs
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GasthausWebApp3Bhwii.Controllers;

public class ProduktController : Controller
{
    // GET
    public IActionResult Index()
    {
        ProduktRepository repo_produkt = new ProduktRepository();
        List<Produkt> myProdukte = repo_produkt.GetAllProdukts();
        
        
        return View(myProdukte);
       
    }
}

GasthausWebApp3Bhwii/Controllers/TischController.cs
using GasthausWebApp3Bhwii.Models;
using GasthausWebApp3Bhwii.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;

namespace GasthausWebApp3Bhwii.Controllers;

public class TischController : Controller
{
    // GET
    public IActionResult Index()
    {
        TischRepository repo_tisch = new TischRepository();
        List<Tisch> mytische = repo_tisch.GetAllTisches();
        
        
        return View(mytische);
        
    }

    public IActionResult New()
    {
        return View();

    }

    [HttpPost]
    public IActionResult SaveTisch(Tisch tisch)
    {
        TischRepository repo_tisch = new TischRepository();
        
        repo_tisch.CreateTisch(tisch);

        return Redirect("/Tisch");
    }
    
}

GasthausWebApp3Bhwii/Views/BestellPosition/Index.cshtml
@model List<BestellPosition>

@{
    ViewData["Title"] = "BestellPosition";
}


<h1>Das sind meine BestellPositionen</h1>
<table>
    <thead>
    <tr>
        <th>BestellPosition</th>
        <th>ProduktId</th>
        <th>BestellId</th>
        <th>Actions</th>
        
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var bestellPosition in Model)
        {
            
            <tr>
                <td>@(bestellPosition.bestellpositionid)</td>
                <td>@(bestellPosition.produktid)</td>
                <td>@(bestellPosition.bestellid)</td>
                <td>Edit Delete</td>
                
                
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Bestellung/Index.cshtml
@model List<Bestellung>

@{
    ViewData["Title"] = "Bestellungen";
}


<h1>Das sind meine Bestellungen</h1>
<table>
    <thead>
    <tr>
        <th>Bestellid</th>
        <th>Preis</th>
        <th>Menge</th>
        <th>Mitarbeiterid</th>
        <th>Tischid</th>
        <th>Gastid</th>
        
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var bestellung in Model)
        {
            
            <tr>
                <td>@(bestellung.bestellid)</td>
                <td>@(bestellung.preis)</td>
                <td>@(bestellung.menge)</td>
                <td>@(bestellung.mitarbeiterid)</td>
                <td>@(bestellung.tischid)</td>
                <td>@(bestellung.gastid)</td>
                
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Gast/Index.cshtml
@model List<Gast>

@{
    ViewData["Title"] = "Gäste";
}


<h1>Das sind meine Gäste</h1>
<table>
    <thead>
    <tr>
        <th>GastId</th>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>Aufenthaltsdauer</th>
       
        
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var gast in Model)
        {
            
            <tr>
                <td>@(gast.Gastid)</td>
                <td>@(gast.vorname)</td>
                <td>@(gast.nachname)</td>
                <td>@(gast.aufenthaltdauer)</td>
                
                
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Home/Index.cshtml
@model List<Tisch>

@{
    ViewData["Title"] = "Home Page";
}

<h1> Das ist meine Website für mein Gasthaus</h1>

GasthausWebApp3Bhwii/Views/Mitarbeiter/Index.cshtml
@model List<Mitarbeiter>

@{
    ViewData["Title"] = "Mitarbeiter";
}


<h1>Das sind meine Verfügbaren Mitarbeiter im Restaurante</h1>
<table>
    <thead>
    <tr>
        <th>MitarbeiterId</th>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>Geburtsdatum</th>
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var mitarbeiter in Model)
        {
            
            <tr>
                <td>@(mitarbeiter.mitarbeiterid)</td>
                <td>@(mitarbeiter.vorname)</td>
                <td>@(mitarbeiter.nachname)</td>
                <td>@(mitarbeiter.geburtsdatum)</td>
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Produkt/Index.cshtml
@model List<Produkt>

@{
    ViewData["Title"] = "Produkte";
}


<h1>Das sind meine Verfügbaren Produkte im Restaurante</h1>
<table>
    <thead>
    <tr>
        <th>ProduktId</th>
        <th>Bezeichnung</th>
        <th>Preis</th>
        <th>Typ</th>
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var produkt in Model)
        {
            
            <tr>
                <td>@(produkt.produktid)</td>
                <td>@(produkt.bezeichnung)</td>
                <td>@(produkt.preis)</td>
                <td>@(produkt.typ)</td>
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Produkt/Indexprodukt.cshtml
@model List<Produkt>

@{
    ViewData["Title"] = "Produkte";
}


<h1>Das sind meine Verfügbaren Produkte im Restaurante</h1>
<table>
    <thead>
    <tr>
        <th>ProduktId</th>
        <th>Bezeichnung</th>
        <th>Preis</th>
        <th>Typ</th>
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var produkt in Model)
        {
            
            <tr>
                <td>@(produkt.produktid)</td>
                <td>@(produkt.bezeichnung)</td>
                <td>@(produkt.preis)</td>
                <td>@(produkt.typ)</td>
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - GasthausWebApp3Bhwii</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/GasthausWebApp3Bhwii.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GasthausWebApp3Bhwii</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Tisch" asp-action="Index">Tische</a>
                        
                    </li>
                    
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Produkt" asp-action="Index">Produkte</a>
                        
                    </li>
                    
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Mitarbeiter" asp-action="Index">Mitarbeiter</a>
                        
                    </li>
                    
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Gast" asp-action="Index">Gäste</a>
                        
                    </li>
                        
                       
                   
                    
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - GasthausWebApp3Bhwii - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GasthausWebApp3Bhwii/Views/Tisch/Index.cshtml
@model List<Tisch>

@{
    ViewData["Title"] = "Tische";
}


<h1>Das sind meine Verfügbaren Tische im Restaurante</h1>
<a href="/Tisch/New" class="btn btn-success">Neunen Tisch erstellen</a>
<table>
    <thead>
    <tr>
        <th>TischId</th>
        <th>Länge</th>
        <th>Breite</th>
        <th>Höhe</th>
    </tr>
    </thead>
    <tbody>
    @{

        foreach (var tisch in Model)
        {
            
            <tr>
                <td>@(tisch.Tischid)</td>
                <td>@(tisch.laenge)</td>
                <td>@(tisch.breite)</td>
                <td>@(tisch.hoehe)</td>
            </tr>
        }

    }
    
    </tbody>
    
</table>

GasthausWebApp3Bhwii/Views/Tisch/New.cshtml
@{
    ViewData["Title"] = "Tische";
}


<h1>Neuen Tisch erstellen</h1>
<form action="/Tisch/SaveTisch" method="post">
    <table class="table">
        <thead>
        <tr>
            <td>Bezeichnung</td>
            <td>Angabe</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>laenge</td>
            <td>
                <input type="number" name="laenge">
            </td>
        </tr>
        <tr>
            <td>breite</td>
            <td>
                <input type="number" name="breite">
            </td>
        </tr>

        <tr>
            <td>hoehe</td>
            <td>
                <input type="number"name="hoehe">
            </td>
        </tr>
        <tr>
            <td>
                <a href="/Tisch" class="btn btn-danger">Abbrechen</a>
            </td>
            <td>
                <button class="btn btn-success" type="submit">Speichern</button>
            </td>
        </tr>
        </tbody>
    </table>
</form>